In [10]:
import os
import os.path as osp
from glob import glob
from tqdm import tqdm
import time
import numpy as np

import torch

## Broadcasting

## Matrix multiplication

In [1]:
import numpy as np

A = np.array([[3, 1, 4], 
              [-2, 0, 1],
              [1, 2, 2]])
B = np.array([[1, 0, 2], 
              [-3, 1, 1], 
              [2, -4, 1]])
A = np.array([[4, 6],
              [2, 1]])
B = np.array([[3, 1, 5],
              [4, 1, 6]])

## Do the matrix multiplication
mat_res = A @ B
# mat_res = A + B
print(mat_res, mat_res.shape)

[[36 10 56]
 [10  3 16]] (2, 3)


In [21]:
mat1 = np.array([[1, 2, 3], 
                 [4, 5, 6]])
mat2 = np.array([[1, 2], 
                 [1, 0], 
                 [0, 1]])

## Do the matrix multiplication
mat_res = mat1 @ mat2
print(mat_res, mat_res.shape)


## For pytorch
mat1 = torch.Tensor([[1, 2, 3], 
                     [4, 5, 6]])
mat2 = torch.Tensor([[1, 2], 
                     [1, 0], 
                     [0, 1]])
mat_res = torch.mm(mat1, mat2)
print(mat_res, mat_res.shape)

mat_res = mat1 @ mat2
print(mat_res, mat_res.shape)

disp = 0
disp += mat1
print(disp, disp.shape)

[[ 3  5]
 [ 9 14]] (2, 2)
tensor([[ 3.,  5.],
        [ 9., 14.]]) torch.Size([2, 2])
tensor([[ 3.,  5.],
        [ 9., 14.]]) torch.Size([2, 2])
tensor([[1., 2., 3.],
        [4., 5., 6.]]) torch.Size([2, 3])


In [ ]:
id_base = np.random.random((18, 80))
id_coeff = np.random.random((1, 80))

id = id_coeff @ id_base.T
print(id.shape)

### dot operation

In [14]:
import numpy as np


v1 = np.array([[1, 2, 3]])
R = np.arange(9).reshape(3, 3)
R = np.array([[7.071071267127990723e-01, -8.124784756091685267e-08, 7.071064710617065430e-01], 
              [4.082483053207397461e-01, -8.164963722229003906e-01, -4.082488417625427246e-01],
              [5.773498415946960449e-01, 5.773506760597229004e-01, -5.773503780364990234e-01]])
print(v1.shape, R.shape)
print(R)

# output = v1.dot(R)
output = v1 @ R
print(output, output.shape)

v1_inv = output @ np.linalg.inv(R)
print(v1_inv)

(1, 3) (3, 3)
[[ 7.07107127e-01 -8.12478476e-08  7.07106471e-01]
 [ 4.08248305e-01 -8.16496372e-01 -4.08248842e-01]
 [ 5.77349842e-01  5.77350676e-01 -5.77350378e-01]]
[[ 3.25565326  0.0990592  -1.84144235]] (1, 3)
[[1. 2. 3.]]


### Big matrix operation

In [54]:
## Conclusion: Pytorch big matrix operations are much faster than numpy's

def matrix_multi_numpy():
    
    id_base = np.random.random((107127, 80))
    id_coeff = np.random.random((75, 80))
    
    start = time.time()
    id_info = id_coeff @ id_base.T
    print(id_info.shape)
    
    end = time.time()
    print(f"matrix_multi_numpy: elapsed time is {end - start}")


def matrix_multi_pytorch():

    id_base = torch.randn((107127, 80))
    id_coeff = torch.randn((75, 80))

    start = time.time()
    for i in range(100):
        id_base_new = id_base.cuda()
        id_coeff_new = id_coeff.cuda()
        # id_info = id_coeff @ id_base.T
        id_info = torch.mm(id_base_new, id_coeff_new.T)

    end = time.time()
    print(f"matrix_multi_pytorch: elapsed time is {(end - start) / 100}")
    

matrix_multi_numpy()


matrix_multi_pytorch()


mean_shape = np.random.random((107127, 1))
disp = np.random.random((75, 107127))

start = time.time()
id_info = mean_shape.reshape(1, -1) + disp
end = time.time()
print(f"elapsed time is {end - start}")

(75, 107127)
matrix_multi_numpy: elapsed time is 0.30770158767700195
matrix_multi_pytorch: elapsed time is 0.06974825859069825
elapsed time is 0.03923201560974121


## Matrix inverse

In [8]:
import numpy as np

extrinsics = "0.970263 0.00747983 0.241939 -191.02 -0.0147429 0.999493 0.0282234 3.28832 -0.241605 -0.030951 0.969881 22.5401 0.0 0.0 0.0 1.0"
extrinsics = np.fromstring(extrinsics, dtype=np.float32, sep=' ')
extrinsics = extrinsics.reshape((4, 4))
print(extrinsics)

mat_inv = np.linalg.inv(extrinsics)
print(mat_inv)

intrinsic = np.array([[2892.33, 0, 823.205, 0],
                      [0, 2883.18, 619.071, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]])

intrinsic = np.array([[100, 0, 12, 0],
                      [0, 5, 10, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]])

mat_inv = np.linalg.inv(intrinsic)
print(mat_inv)

[[ 9.70263e-01  7.47983e-03  2.41939e-01 -1.91020e+02]
 [-1.47429e-02  9.99493e-01  2.82234e-02  3.28832e+00]
 [-2.41605e-01 -3.09510e-02  9.69881e-01  2.25401e+01]
 [ 0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00]]
[[ 9.7026235e-01 -1.4742792e-02 -2.4160510e-01  1.9083380e+02]
 [ 7.4799401e-03  9.9949282e-01 -3.0950988e-02 -1.1601957e+00]
 [ 2.4193870e-01  2.8223433e-02  9.6988088e-01  2.4261110e+01]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]]
[[ 0.01  0.   -0.12  0.  ]
 [ 0.    0.2  -2.    0.  ]
 [ 0.    0.    1.    0.  ]
 [ 0.    0.    0.    1.  ]]


## Determinant

In [3]:
import numpy as np

A = np.array([[0, 1, 1], [1, 0, 1], [2, 3, 4]])
A = np.array([[1, 2, 1],
              [2, 4, 2],
              [1, 1, 1]])

print(np.linalg.det(A))

0.0
